











# This is a basic workflow to help you get started with Actions

name: CI/CD-AWS
env:
  EB_S3_bucket_name: "my22bucket-pyapp"
  EB_app_name      : "flask_App"
  EB_env           : "flask_App-env"
  Deploy_pack_name : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME  : "us-east-1"
  
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v1
      

      # Runs a single command using the runners shell
      - name: Zip deploy package
        run: zip -r ${{env.Deploy_pack_name}} ./ *.git*

      # Runs a set of commands using the runners shell
      - name: Config Cred
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id    :  ${{ secrets.AWS_AK_FLASK }}
          aws-secret-access-key:  ${{ secrets.AWS_SK_FLASK }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}
      
      - name: Copy Deployment package to S3 bucket
        run : aws s3 cp ${{ env.Deploy_pack_name }}  s3://${{ env.EB_S3_bucket_name }}/
    
      - name: Print Happy Message for CI finish
        run : echo "CI Pipeline part Finished successfully!"


  CD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [CI]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Config Cred
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id    :  ${{ secrets.AWS_AK_FLASK }}
          aws-secret-access-key:  ${{ secrets.AWS_SK_FLASK }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}
      
      - name: Create new ElasticBeanstalk Application Version
        run : |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_app_name }} \
          --source-bundle S3Bucket="${{ env.EB_S3_bucket_name }}",S3Key="${{ env.Deploy_pack_name }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CoimmitSHA-${{ github.sha }}"
       
      - name: Deploy new ElasticBeanstalk Application Version
        run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_env }} --version-label "Ver-${{ github.sha }}"
      
      - name: Print Happy Message for CD finish
        run : echo "CD Pipeline part Finished successfully!"


